language: android
sudo: required
android:
  components:
  - tools
  - build-tools-24.0.2
  - android-24
  - extra
jdk:
  - oraclejdk8
env:
  global:
  - END_TASK=""
script:
  - if [[ "${TRAVIS_PULL_REQUEST}" = "false" ]]; then
      export END_TASK="uploadArchives";
    fi
  - ./gradlew clean jacocoTestReport coveralls
  - ./gradlew clean assemble ${END_TASK}
before_install:
  - if [[ "${TRAVIS_PULL_REQUEST}" = "false" ]]; then
      openssl aes-256-cbc -K $encrypted_56349c9a6208_key -iv $encrypted_56349c9a6208_iv -in gradle.properties.enc -out gradle.properties -d;
    fi
